# Change these first
owner: sonicverse-eu # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:

  - name: Dokploy - Dashboard
    url: https://dokploy.sonicverse.eu
    type: globalping
    location: rikvisser-dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sonicverse.eu
  # baseUrl: /your-repo-name
  logoUrl: https://sonicverse.fsn1.your-objectstorage.com/branding/icon.svg
  name: Sonicverse
  introTitle: "Sonicverse StatusPage"
  introMessage: Welcome to the Sonicverse StatusPage, where we'll keep you up-to-date about the status of our services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
